/**
 * Open Source model-chatGPT, gemini, calude
 * closed Source Model-Mistral, LLaMA, Deep Seek , phi, Qwen, Kimi k2
 * What is the Google Antigravity?
 * It is the AI -Powered integrated Development envirnment(IDE)
 * or IDE - that was released alongside Gemini 3 in November 2025.
 *Prompt Engineering - It is the practice of designing and refining inputs (prompts)
 * to effectively communicate with Large Language Models (LLMs) to achieve desired outputs.

*What is Javascript?*=>A website is built with three core technologies
JavaScript is a runtime language that uses JIT compilation internally for performance.

- **HTML** — Structure / Content
- **CSS** — Styling / Appearance
- **JavaScript** — Behavior / Interactivity
 ** It supports object-oriented, functional, and Event-driven programming styles**

*Java. vs Javascript
*int a=10;//java     let a=10;//javascript

*Javascript vs Typescript
*Javascript -> let a = 10; --> a="Pramod";//valid
*TypeScript ->  let a:number = 10;

*What is[Node.js](http://node.js/)?
- Node.js is an open-source, cross-platform JavaScript runtime environment that allows you
 to run JavaScript code outside of a web browser primarily on servers.
- It was created by **Ryan Dahl in 2009** and is built on Google Chrome's V8 JavaScript
 engine.
*
*How the javaScript engine Works?
JavaScript Engine Are the program that reads, interprets and executes javascript code.
It also manages memory, optimizes code execution, and handles the call stack during program execution.
the engine is responsible for the conversion of javaScript code into machine code dt the computer can 
understand & execute.

Suppoese u write a code :let a=10;
Step 1:Lexical Analysis(Tokan generating)[let][a][=][10][;]
Step 2:Parsing(the engine 1st reads ur javascript code, syntax, variables,Identifiers & semicolan)            Step 3:Create AST(Abstract Syntax tree-The AST represents the structure of your program)
Step 4:Interpreter(Convert AST to Byte Code- that Human Cannot Understand)System generated code
Step 5:Execution (Whenever a function is called, it is pushed onto the Call Stack.)
Step 6: Profiler+JIT Optimization.(TurboFan/Compiler-> Compiler convert or optimize the code of the 
         Hot code.-> ByteCode.
Step 7:Garbage Collector(Unused memory is automatically removed using Garbage Collection.)
Step 8:Machine Code Execution (The final optimized code is executed directly by the CPU. 
This gives the best performance at runtime).

What is Source Code?-it the human-readable code that programmers Write in programming languages like java.
What is Byte Code? it is the intermediate code generated by the Js Engine.
What is Binary Code?010101010-binary code is also called machine code,which is actually understood by the real machines or our chips 












 */

